---
title: "GreenFeed Final Data Report"
date: "`r format(Sys.Date(), '%Y-%m-%d')`"
output: pdf_document
---

```{r libraries, include=FALSE}

library(dplyr)
library(tidyverse)
library(lubridate)
library(ggplot2)
library(RColorBrewer)
library(reshape2)
library(gridExtra)
library(plyr)
library(ggpubr)
library(reshape2)
library(kableExtra)

```

# Study: `r Exp`

## GreenFeed unit(s): `r Unit`

## Days of experiment: `r floor(as.numeric(difftime(max(df$StartTime), min(as.Date(df$StartTime)), units = "days") +1))` days

**Number of animals with records: `r length(unique(df$RFID))`**


\newpage


## **Daily gases records**


```{r Data per cow, message=FALSE, echo=FALSE, fig.height=4.2, fig.width=7}

cols_to_convert <- c("CH4GramsPerDay", "CO2GramsPerDay", "O2GramsPerDay", "H2GramsPerDay")
df[cols_to_convert] <- lapply(df[cols_to_convert], as.numeric)

#Plot 1: Total number of production records per day
plot1 <- ggplot(as.data.frame(table(as.Date(df$StartTime))), aes(x = Var1, y = Freq)) + 
  geom_col(color = "black") +
  labs(title = "Total records per day", x = "", y = "Number of records") +
  geom_text(aes(label = Freq), vjust = -0.5, color = "black", size = 2.2, position = position_dodge(width = 0.9)) +
  theme_classic() +
  theme(plot.title = element_text(size = 11, face = "bold"),
        axis.text.x = element_text(angle = 45, hjust = 1.05, size = 8),
        axis.title.y = element_text(size = 10, face = "bold"),
        legend.position = "none")

plot1


df_normalized <- df %>%
  mutate(Normalized_CH4 = scale(CH4GramsPerDay),
         Normalized_CO2 = scale(CO2GramsPerDay),
         Normalized_O2 = scale(O2GramsPerDay),
         Normalized_H2 = scale(H2GramsPerDay))

# Create the combined plot
combined_plot <- ggplot(df_normalized[df_normalized$HourOfDay <= 23, ], aes(x = HourOfDay)) + 
  geom_point(aes(y = Normalized_CH4), color = "#E0E0E0") +
  geom_point(aes(y = Normalized_CO2), color = "#E0E0E0") +
  geom_point(aes(y = Normalized_O2), color = "#E0E0E0") +
  geom_point(aes(y = Normalized_H2), color = "#E0E0E0") +
  geom_smooth(aes(y = Normalized_CH4, color = "CH4"), se = FALSE) +
  geom_smooth(aes(y = Normalized_CO2, color = "CO2"), se = FALSE) +
  geom_smooth(aes(y = Normalized_O2, color = "O2"), se = FALSE) +
  geom_smooth(aes(y = Normalized_H2, color = "H2"), se = FALSE) +
  theme_classic() +
  theme(plot.title = element_text(size = 11, face = "bold"),
        axis.text.x = element_text(angle = 0, size = 9),
        axis.text.y = element_text(angle = 0, size = 9),
        axis.title.y = element_text(size = 10, face = "bold"),
        axis.title.x = element_text(size = 10, face = "bold"),
        legend.position = "bottom") +
  labs(title = "Normalized gas production across the day",
       x = "Hour of Day",
       y = "Normalized Value",
       color = "Gas type") +
  scale_x_continuous(breaks = seq(0, 23), labels = c("12 AM", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", 
                                                     "12 PM", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11")) +
  scale_color_manual(values = c("CH4" = "blue", "CO2" = "red", "O2" = "green", "H2" = "orange"))


combined_plot

```


\newpage

## **Daily gas records per animal**

```{r Data per day, message=FALSE, warning=FALSE, echo=FALSE, fig.height=4, fig.width=7}

## Description of total number of records and CH4 PER COW

#Plot 1: Total number of records per cow
plot1 <- df %>%
  dplyr::mutate(day = as.Date(EndTime)) %>%
  
  dplyr::group_by(RFID, day) %>%
  dplyr::summarise(n = n(), 
                   daily_CH4 = weighted.mean(CH4GramsPerDay, GoodDataDuration, na.rm = TRUE)) %>%
  
  dplyr::group_by(RFID) %>%
  dplyr::summarise(n = sum(n), 
                   daily_CH4 = mean(daily_CH4, na.rm = TRUE)) %>%
  
  ggplot(aes(x = reorder(RFID, -daily_CH4), y = n)) + 
    geom_bar(stat = "identity", position = position_dodge()) +
    labs(title = "Total records per cow", x = "", y = "Number of records", fill = "") +
    theme_classic() +
    theme(plot.title = element_text(size = 11, face = "bold"),
        axis.text.x = element_text(angle = 45, hjust = 1.05, size = 5),
        axis.title.y = element_text(size = 10, face = "bold"),
        legend.position = "none") +
  
    #geom_hline(yintercept = floor(as.numeric(difftime(max(df$StartTime), min(df$StartTime), units = "days"))),
    #         linetype = "dashed", color = "red", linewidth = 0.5) +
    geom_text(aes(label = n), vjust = -1, color = "black",
            position = position_dodge(width = 0.9), size = 2.2)


##Changing the format of the hour of the day
df$HourOfDay <- as.numeric(df$HourOfDay)

plot2 <- df %>%
  mutate(AMPM = case_when(
    HourOfDay >= 22 ~ "10PM - 4AM",
    HourOfDay < 4 ~ "10PM - 4AM",
    HourOfDay >= 4 & HourOfDay < 10 ~ "4AM - 10AM",
    HourOfDay >= 10 & HourOfDay < 16 ~ "10AM - 4PM",
    HourOfDay >= 16 & HourOfDay < 22 ~ "4PM - 10PM",
    TRUE ~ NA_character_)) %>%
  
  dplyr::group_by(RFID, AMPM) %>%
  dplyr::summarise(n = n()) %>%
  
  ggplot(aes(x = RFID, y = n, fill = factor(AMPM, levels = c("10PM - 4AM", "4AM - 10AM", "10AM - 4PM", "4PM - 10PM")))) +
  geom_bar(stat = "identity", position = "fill") +
  labs(title = "Distribution of records across the day per cow", x = "", y = "Percentage of total records", fill = "") +
  theme_classic() +
  theme(plot.title = element_text(size = 11, face = "bold"),
        axis.text.x = element_text(angle = 45, hjust = 1.05, size = 5),
        legend.position = "bottom",
        axis.title.y = element_text(size = 10, face = "bold")) +
  scale_fill_brewer(palette = "BrBG") +
  scale_y_continuous(breaks = c(0, 0.25, 0.50, 0.75, 1), labels = c("0%", "25%", "50%", "75%", "100%"), expand = c(0, 0))


plot1
plot2

```


\newpage

## **Daily gas production per animal**

```{r Gas data production per cow, message=T, warning=FALSE, echo=FALSE, fig.height=3, fig.width=7}

## The daily averages for different gases is calculated as the weighted mean using visit time to the GreenFeed (or 'GoodDataDuration')

#Plot 1: Methane production per cow
plot1 <- df %>%
  dplyr::mutate(day = as.Date(EndTime)) %>%
  dplyr::group_by(RFID, day) %>%
  dplyr::summarise(daily_CH4 = weighted.mean(CH4GramsPerDay, GoodDataDuration, na.rm = TRUE)) %>%
  
  {ggplot(., aes(x = reorder(RFID, -daily_CH4), y = daily_CH4, color = daily_CH4)) + 
      geom_boxplot(fatten = NULL, outlier.shape = NA) +
      stat_summary(fun = mean, geom = "errorbar", aes(ymax = ..y.., ymin = ..y..), width = 0.75, size = 0.7, color = "black", linetype = "solid") +
      
      labs(title = "Methane (CH4) production per animal", x = "", y = "CH4 (g/d)") +
      
      theme_classic() +
      theme(plot.title = element_text(size = 11, face = "bold"),
        axis.text.x = element_text(angle = 45, hjust = 1.05, size = 5),
        axis.title.y = element_text(size = 10, face = "bold"),
        legend.position = "none") +
      
      geom_hline(yintercept = mean(.$daily_CH4), linetype = "dashed", color = "blue", linewidth = 0.6) +
      scale_y_continuous(breaks = seq(0, max(.$daily_CH4), by = 100))
    }


#Plot 2: Carbon dioxide production per cow
plot2 <- df %>%
  dplyr::mutate(day = as.Date(EndTime)) %>%
  dplyr::group_by(RFID, day) %>%
  dplyr::summarise(daily_CO2 = weighted.mean(CO2GramsPerDay, GoodDataDuration, na.rm = TRUE)) %>%
  
  {ggplot(., aes(x = reorder(RFID, -daily_CO2), y = daily_CO2, color = daily_CO2)) + 
      geom_boxplot(fatten = NULL, outlier.shape = NA) +
      stat_summary(fun = mean, geom = "errorbar", aes(ymax = ..y.., ymin = ..y..), width = 0.75, size = 0.7, color = "black", linetype = "solid") +
      
      labs(title = "Carbone dioxide (CO2) production per animal", x = "", y = "CO2 (g/d)") +
      
      theme_classic() +
      theme(plot.title = element_text(size = 11, face = "bold"),
        axis.text.x = element_text(angle = 45, hjust = 1.05, size = 5),
        axis.title.y = element_text(size = 10, face = "bold"),
        legend.position = "none") +
      
      geom_hline(yintercept = mean(.$daily_CO2), linetype = "dashed", color = "red", linewidth = 0.6) +
      scale_y_continuous(breaks = seq(0, max(.$daily_CO2), by = 2000))
    }


#Plot 3: Oxygen production per cow
plot3 <- df %>%
  dplyr::mutate(day = as.Date(EndTime)) %>%
  dplyr::group_by(RFID, day) %>%
  dplyr::summarise(daily_O2 = weighted.mean(O2GramsPerDay, GoodDataDuration, na.rm = TRUE)) %>%
  
  {ggplot(., aes(x = reorder(RFID, -daily_O2), y = daily_O2, color = daily_O2)) + 
      geom_boxplot(fatten = NULL, outlier.shape = NA) +
      stat_summary(fun = mean, geom = "errorbar", aes(ymax = ..y.., ymin = ..y..), width = 0.75, size = 0.7, color = "black", linetype = "solid") +
      
      labs(title = "Oxygen (O2) production per animal", x = "", y = "O2 (g/d)") +
      
      theme_classic() +
      theme(plot.title = element_text(size = 11, face = "bold"),
        axis.text.x = element_text(angle = 45, hjust = 1.05, size = 5),
        axis.title.y = element_text(size = 10, face = "bold"),
        legend.position = "none") +
      
      geom_hline(yintercept = mean(.$daily_O2), linetype = "dashed", color = "green", linewidth = 0.6) +
      scale_y_continuous(breaks = seq(0, max(.$daily_O2), by = 2000))
    }


#Plot4: Hydrogen production per cow

if (any(df$H2GramsPerDay > 0)) {

  plot4 <- df %>%
  dplyr::mutate(day = as.Date(EndTime)) %>%
  dplyr::group_by(RFID, day) %>%
  dplyr::summarise(daily_H2 = weighted.mean(H2GramsPerDay, GoodDataDuration, na.rm = TRUE)) %>%
  
  {ggplot(., aes(x = reorder(RFID, -daily_H2), y = daily_H2, color = daily_H2)) + 
      geom_boxplot(fatten = NULL, outlier.shape = NA) +
      stat_summary(fun = mean, geom = "errorbar", aes(ymax = ..y.., ymin = ..y..), width = 0.75, size = 0.7, color = "black", linetype = "solid") +
      
      labs(title = "Hydrogen (H2) production per animal", x = "", y = "H2 (g/d)") +
      
      theme_classic() +
      theme(plot.title = element_text(size = 11, face = "bold"),
        axis.text.x = element_text(angle = 45, hjust = 1.05, size = 5),
        axis.title.y = element_text(size = 10, face = "bold"),
        legend.position = "none") +
      
      geom_hline(yintercept = mean(.$daily_H2), linetype = "dashed", color = "orange", linewidth = 0.6) +
      scale_y_continuous(breaks = seq(0, max(.$daily_H2), by = 0.5))
    }

} else {
  
  plot4 <- "No hydrogen (H2) data from GreenFeed"
  
}


plot1 #Methane
plot2 #Carbon dioxide
plot3 #Oxygen
plot4 #Hydrogen

```

