#' @title finalrep
#' @name finalrep
#' @description Report final GreenFeed data
#'
#' @param Exp Study name
#' @param Unit The unit number/s of the GreenFeed
#' @param Start_Date Start date of the study
#' @param End_Date End date of the study
#' @param Final_report List with final report/s generated by C-Lock
#' @param Plot_opt Type of gas to plot: All, CH4, CO2, O2, or H2. If not specified, only CH4 will be process
#'
#' @return A PDF report with description of final GreenFeed data.
#'
#' @examples
#' \dontrun{
#' Exp <- "StudyName"
#' Unit <- 1
#' Start_Date <- "2024-01-22"
#' End_Date <- "2024-03-08"
#' Final_report <- list(system.file("extdata", "StudyName_FinalReport.xlsx", package = "greenfeedr"))
#'
#' finalrep(Exp, Unit, Start_Date, End_Date, Final_report)
#' }
#'
#' @export finalrep
#'
#' @import dplyr
#' @importFrom dplyr %>%
#' @import lubridate
#' @import readr
#' @import readxl
#' @import rmarkdown
#' @import utils

utils::globalVariables(c("GoodDataDuration", "AirflowLitersPerSec", "CH4GramsPerDay"))

finalrep <- function(Exp = NA, Unit = NA, Start_Date = NA, End_Date = NA,
                     Final_report = list(NA), Plot_opt = "CH4") {
  # Function to read and process each file
  process_file <- function(file) {
    df <- readxl::read_excel(file, col_types = c("text", "text", "numeric", rep("date", 3), rep("numeric", 12), "text", rep("numeric", 6)))
    names(df)[1:14] <- c(
      "RFID",
      "FarmName",
      "FeederID",
      "StartTime",
      "EndTime",
      "GoodDataDuration",
      "HourOfDay",
      "CO2GramsPerDay",
      "CH4GramsPerDay",
      "O2GramsPerDay",
      "H2GramsPerDay",
      "H2SGramsPerDay",
      "AirflowLitersPerSec",
      "AirflowCf"
    )

    # df contains finalized GreenFeed data
    df <- df %>%
      # Remove leading zeros from RFID col to match with IDs
      dplyr::mutate(RFID = gsub("^0+", "", RFID)) %>%
      # Change the format of good data duration column to minutes with two decimals
      dplyr::mutate(GoodDataDuration = round(lubridate::period_to_seconds(lubridate::hms(format(as.POSIXct(GoodDataDuration), "%H:%M:%S"))) / 60, 2)) %>%
      # Remove data with Airflow below the threshold (25 l/s) and data in the time range selected
      dplyr::filter(
        AirflowLitersPerSec >= 25,
        StartTime >= Start_Date & StartTime <= End_Date
      )

    return(df)
  }

  # Combine all final report files into one data frame
  df <- do.call(rbind, lapply(Final_report, process_file))

  # Create PDF report using Rmarkdown
  rmarkdown::render(
    input = system.file("FinalReportsGF.Rmd", package = "greenfeedr"),
    output_file = file.path(getwd(), paste0("Report_", Exp, ".pdf"))
  )
}
