#' @name finalrep
#' @title Report Final GreenFeed Data
#'
#' @description `finalrep()` generates a final report for GreenFeed data, summarizing key metrics
#'     and providing a comprehensive overview of the collected data.
#'     This report includes analysis and visualizations to assist in evaluating
#'     the performance and outcomes of the GreenFeed units.
#'
#' @param exp Study name
#' @param unit The unit number(s) of the GreenFeed. If multiple units, they could be in a vector, list, or character as "1,2"
#' @param start_date Start date of the study
#' @param end_date End date of the study
#' @param final_report List with final report(s) generated by C-Lock
#' @param plot_opt Type of gas to plot: All, or CH4, CO2, O2, H2. By default only CH4 will be processed and reported
#' @param RFID_file The file that contains the RFID of the animals in the study
#'
#' @return A PDF report with description of the final records.
#'
#' @examples
#' # Create a Final Report in PDF format from the finalized data received from C-Lock Inc.
#' # Define parameters:
#' Experiment <- "StudyName"
#'
#' # Note that Unit could be numeric or character (It will use to print in the PDF)
#'
#' # File is a list of reports from C-Lock inc.
#' # it could be one or multiples depend on the number of units
#' file <- list(system.file("extdata", "StudyName_FinalReport.xlsx", package = "greenfeedr"))
#'
#' # By default `finalrep()` plot only methane (CH4), but here we defined to plot "All" gases
#'
#' # Is it possible to include a file with Farm IDs to use in the reports
#' # The file structure should be: FarmName | RFID
#'
#' finalrep(
#'   exp = Experiment,
#'   unit = 1,
#'   start_date = "2024-05-13",
#'   end_date = "2024-05-25",
#'   save_dir = tempdir(),
#'   final_report = file,
#'   plot_opt = "All",
#'   RFID_file = NA
#' )
#'
#' @export finalrep
#'
#' @import dplyr
#' @importFrom dplyr %>%
#' @import lubridate
#' @import readr
#' @import readxl
#' @import rmarkdown
#' @import utils

utils::globalVariables(c("GoodDataDuration", "AirflowLitersPerSec"))

finalrep <- function(exp, unit, start_date, end_date, save_dir = getwd(),
                     final_report = list(NA), plot_opt = "CH4", RFID_file = NA) {
  # Check Date format
  start_date <- ensure_date_format(start_date)
  end_date <- ensure_date_format(end_date)

  # Function to read and process each file
  process_file <- function(file) {
    df <- readxl::read_excel(file, col_types = c("text", "text", "numeric", rep("date", 3), rep("numeric", 12), "text", rep("numeric", 6)))
    names(df)[1:14] <- c(
      "RFID",
      "AnimalName",
      "FeederID",
      "StartTime",
      "EndTime",
      "GoodDataDuration",
      "HourOfDay",
      "CO2GramsPerDay",
      "CH4GramsPerDay",
      "O2GramsPerDay",
      "H2GramsPerDay",
      "H2SGramsPerDay",
      "AirflowLitersPerSec",
      "AirflowCf"
    )

    # df contains finalized GreenFeed data
    df <- df %>%
      # Remove leading zeros from RFID col to match with IDs
      dplyr::mutate(
        RFID = gsub("^0+", "", RFID),
        # Extract hours, minutes, and seconds from GoodDataDuration
        GoodDataDuration = round(
          as.numeric(substr(GoodDataDuration, 12, 13)) * 60 + # Hours to minutes
            # as.numeric(substr(GoodDataDuration, 1, 2)) * 60 +  # Hours to minutes
            as.numeric(substr(GoodDataDuration, 15, 16)) + # Minutes
            # as.numeric(substr(GoodDataDuration, 4, 5)) +
            as.numeric(substr(GoodDataDuration, 18, 19)) / 60, # Seconds to minutes
          # as.numeric(substr(GoodDataDuration, 7, 8)) / 60,
          2
        )
      ) %>%
      # Remove data with Airflow below the threshold (25 l/s) and data in the time range selected
      dplyr::filter(
        AirflowLitersPerSec >= 25,
        as.Date(StartTime) >= as.Date(start_date) & as.Date(StartTime) <= as.Date(end_date)
      )

    return(df)
  }

  # Combine all final report files into one data frame
  df <- do.call(rbind, lapply(final_report, process_file))

  # Read file with the RFID in the study
  if (!is.na(RFID_file)) {
    if (tolower(tools::file_ext(RFID_file)) == "csv") {
      RFID_file <- readr::read_table(RFID_file, col_types = readr::cols(FarmName = readr::col_character(), RFID = readr::col_character()))
    } else if (tolower(tools::file_ext(RFID_file)) %in% c("xls", "xlsx")) {
      RFID_file <- readxl::read_excel(RFID_file, col_types = c("text", "text", "numeric", "text"))
    } else {
      stop("Unsupported file format.")
    }
  }

  # If RFID file is provided then perform inner join
  if (!is.null(RFID_file) && is.data.frame(RFID_file) && nrow(RFID_file) > 0) {
    df <- dplyr::inner_join(df, RFID_file, by = "RFID")
  }

  # Create PDF report using Rmarkdown
  rmarkdown::render(
    input = system.file("FinalReportsGF.Rmd", package = "greenfeedr"),
    output_file = file.path(save_dir, paste0("FinalReport_", exp, ".pdf"))
  )
}
