# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

permissions: read-all

jobs:
  setup-latex:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - {os: macos-latest}
          - {os: windows-latest}
          - {os: ubuntu-latest}

    steps:
      - uses: actions/checkout@v4

      - name: Install TinyTeX (for LaTeX) on Ubuntu
        if: matrix.config.os == 'ubuntu-latest'
        run: |
          R -e "install.packages('tinytex')"
          R -e "tinytex::install_tinytex()"

      - name: Install TinyTeX (for LaTeX) on macOS
        if: matrix.config.os == 'macos-latest'
        run: |
          Rscript -e 'install.packages("tinytex"); tinytex::install_tinytex()'
          sudo tlmgr update --self --all || true
        shell: bash

      - name: Install TinyTeX (for LaTeX) on Windows
        if: matrix.config.os == 'windows-latest'
        run: |
          echo "Starting TinyTeX installation on Windows..."
          Rscript -e 'if (tinytex::is_tinytex()) tinytex::uninstall_tinytex()'
          Rscript -e 'install.packages("tinytex", repos="https://cran.rstudio.com/")'
          Rscript -e 'tinytex::install_tinytex()'
          Rscript -e 'tinytex::tlmgr_install(c("latexmk", "pdftex", "xetex", "luatex"))'
          echo "TinyTeX installation completed."
        shell: bash

  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    needs: setup-latex

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'oldrel-1'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - name: Print Session Info
        run: Rscript -e "sessionInfo()"
        shell: Rscript {0}

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
