# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check.yaml

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'oldrel-1'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - name: Install TinyTeX (for LaTeX)
        if: matrix.config.os == 'ubuntu-latest'
        run: |
          R -e "install.packages('tinytex')"
          R -e "tinytex::install_tinytex()"

      - name: Install TinyTeX (for LaTeX)
        if: matrix.config.os == 'macos-latest'
        run: |
          Rscript -e 'install.packages("tinytex"); tinytex::install_tinytex()'
          sudo tlmgr update --self --all || true
        shell: bash

      - name: Install TinyTeX (for LaTeX)
        if: matrix.config.os == 'windows-latest'
        run: |
          Rscript -e 'install.packages("tinytex", repos="https://cran.rstudio.com/")'
          Rscript -e 'tinytex::install_tinytex(force = TRUE)'
          Rscript -e 'tinytex::tlmgr_install("latexmk")'
          Rscript -e 'tinytex::tlmgr_install(c("xcolor", "amsmath", "babel", "hyperref", "geometry", "graphicx", "grffile", "fancyhdr", "longtable", "wrapfig", "rotating", "ulem", "amsfonts", "capt-of", "fontenc", "textcomp", "amssymb", "appendix", "pdfpages", "booktabs"))'
          tlmgr update --self --all || true
        shell: bash

      - name: Ensure LaTeX is available
        run: |
          pdflatex --version || echo "LaTeX is not installed correctly"
        shell: bash

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
